### ISSUE TITLE
Design and implement URLs

### ISSUE THREAD

**Issue by natbat** [natbat/tidepools_near_me#6]
`/` should redirect `/us/pillar-point`

**Comment by simonw** [comment]
https://www.rockybeaches.com/ now points at the Vercel deployment.

**Comment by simonw** [comment]
https://www.rockybeaches.com/ now redirects to https://www.rockybeaches.com/us/pillar-point using this monstrous piece of ASGI trickery:

https://github.com/natbat/tidepools_near_me/blob/ec102c6da5a5d86f17628740d90b6365b671b5e1/plugins/urls.py#L1-L19
